### ISSUE TITLE
Laravel 11.x support

### ISSUE THREAD

**Issue by denniseilander** [denniseilander/laravel-passport-scopes-restriction#45]

**Comment by thuijbers** [comment]
Hi Dennis! Wanneer verwacht je dat deze doorgevoerd kan worden?

**Comment by denniseilander** [comment]
Hi @thuijbers, ik heb hier nog weinig tijd voor gemaakt, maar ik zal proberen dit vandaag door te voeren 👍

**Comment by denniseilander** [comment]
Hi @thuijbers,

Ik heb versie 3.0.0 getagged waarin Laravel 11 support zit. Door een grote upgrade vanuit Laravel Passport was ik genoodzaakt om Laravel 10 support te droppen, vandaar de major release.

Laat me vooral weten als je problemen ervaart met deze nieuwe versie.

**Comment by thuijbers** [comment]
@denniseilander super! Bedankt voor de snelle reactie!
